### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by DanCNo** [DanCNo/best_reads#3]
## User Auth

- [x] MVP is completely styled and seeded
- [x] MVP is bug free with smooth navigation
- [x] MVP is bug free on a hard refresh (⌘ + R)
- [x] MVP handles errors with informative messages for user

### Additional Features
- [x] Users can sign up, log in, log out
- [x] Users can use a demo login to try the site
- [x] Reserved content for logged in users is intended to be displayed on the home page

### Additional Notes:
N/A

**Comment by david-dickinson** [comment]
- [ ] Right now, errors are rendering near the signup page whether they originate from signup or login. I'd mirror Goodreads' functionality, where errors redirect users to a specific `/login` or `/signup` page with errors, so it's clearer where the error comes from.

**Comment by DanCNo** [comment]
@david-dickinson I've completed the specific /login and /signup pages.

**Comment by david-dickinson** [comment]
- [ ] Last thing - style the demo user button to fit with the page more. Otherwise, nice work!

**Comment by DanCNo** [comment]
@david-dickinson Completed demo login styling.
